# Generated by Django 3.2.20 on 2023-08-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postImg',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name=''),
        ),
    ]
