# Generated by Django 3.2.20 on 2023-08-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postTime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name=''),
        ),
    ]
