# Generated by Django 3.2.20 on 2023-08-24 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0010_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='profileImg',
            field=models.ImageField(blank=True, null=True, upload_to=None, verbose_name='pp'),
        ),
    ]
